### ISSUE TITLE
carcass estimates - confirm run and adipose clipped

### ISSUE THREAD

**Issue by alvizek** [SRJPE/JPE-datasets#153]
For the carcass estimates data, we need to confirm the run and the adipose status for the data we have (prioritize the data that we think we will use for JPE, Feather and Butte).

**Comment by liz-fw** [comment]
Butte notes:

- carcass survey is performed for spring run (https://www.calfish.org/ProgramsData/ConservationandManagement/CentralValleyMonitoring/SacramentoValleyTributaryMonitoring/ButteCreek.aspx) so assume that all are `spring`. 
- two types of files for each year `2014-2020` - individuals and chops. Individuals record `adipose_fin_clip` and so do chops. 
- historical estimates in an excel have the results from modeling for `2001-2020`, which fill in earlier years but do not have any associated `adipose_fin_clipped` data. These are not included in `standard_carcass`. 
- individual data from `2019` does not have dates in the raw file.

**Comment by liz-fw** [comment]
Feather notes:

- Data collected from `2000-2020`
- According to notes, `run` was collected for all years but is only present in `2009` and `2017-2021`
- According to notes, `adipose_fin_clipped` was collected for all years. Due to misalignment of header tables and data tables, there are many `NA` dates associated with `adipose_fin_clipped` in the final file and no way of recovering these easily.
- Reviewed by year. `2000-2001` does not collect either variable. Run not collected for `2010-2016`
- Fixed joining of cwt data with cwt header (date) for 2008, 2002, 2003, 2004 (still some missing dates due to misaligned header IDs), 2005 (some missing dates same as 2004), 2006 (some dates missing), 2007 (some dates missing)
- Some dates missing in 2009 because of missing some matching header IDs in chopChannel with ChopChannel_header

**Comment by liz-fw** [comment]
TODO:

- [ ] re-run feather carcass standard .Rmd - double check ad fin clip and run by year

**Comment by liz-fw** [comment]
in branch `carcass-dat-achecks`:

- ensured all available `adipose_fin_clip` and `run` data were incorporated into `feather_carcass`
- added `run` and `adipose_fin_clip` to Butte carcass where available - mostly going off reports

**Comment by liz-fw** [comment]
TODO:

- [ ] Battle
- [ ] Clear
- [ ] Yuba

**Comment by liz-fw** [comment]
Battle Creek: spring run and unknown covered by survey but not recorded in data, so marked `run` as `NA`. `adipose_fin_clipped` recorded.

**Comment by liz-fw** [comment]
TODO

- [ ] track down NA dates for Butte

**Comment by liz-fw** [comment]
- kept `2019` Butte data in the final standard dataset by mutating a fake date (`2019-01-01`) for those data - confirm this is what we want to do, otherwise they get filtered out

**Comment by liz-fw** [comment]
associated branch: `carcass-dat-achecks` (typo is mine, oops)

**Comment by liz-fw** [comment]
Action items:

- [ ] Reach out to Grant and confirm 2019 dates
- [ ] Does 2019 include both pre-spawn and post-spawn surveys (we don't want to sum all if so)
- [ ] Is CJS run on hatchery/natural ?

**Comment by liz-fw** [comment]
e-mails sent to Grant and Keith 11-28-2023

**Comment by liz-fw** [comment]
- [ ] need to follow up with Grant on e-mail chain to ask about the CJS confidence intervals.
