### ISSUE TITLE
holding data - confirm run and adipose clipped

### ISSUE THREAD

**Issue by alvizek** [SRJPE/JPE-datasets#155]
We need to confirm the run and adipose clipped status of the holding data or if unknown we need to include that.

**Comment by liz-fw** [comment]
associated branch: `holding-data-checks`

**Comment by liz-fw** [comment]
@alvizek I changed deer `adipose_clipped` to `F` and other streams to `not recorded`. 

re: double counting checks, butte creek counts are already processed to be averaged across date and reach. Battle and Clear both have multiple rows for many date/reach combinations. I think the next steps should be:

- [ ] for Battle, group by date and reach and take the average because in the adult data report, Battle's methods state "Three snorkelers swim perpendicular to the flow and count holding Chinook, carcasses and redds.". 
- [ ] for Clear, group by date and reach and take the average. According to methods, "Moving
downstream with the current, three snorkelers counted adult Chinook, Chinook carcasses, and
Chinook redds... Generally, snorkelers were adjacent to each other in a line
perpendicular to the flow and would keep track of individual counts within their lane or area of
the creek. As needed, snorkelers would confer with each other to make sure no salmon were
missed or double counted and then sum and record their counts." (https://www.noaa.gov/sites/default/files/legacy/document/2020/Oct/07354626154.pdf page 4)

There is no additional information in the raw data files that would further distinguish the multiple rows, except in Clear the `notes` column has `WP XYZ` values (likely waypoint) that are mostly distinct

**Comment by alvizek** [comment]
Ashley and Liz discussed and decided to ask data stewards during the Adult Next Steps meeting.

**Comment by alvizek** [comment]
Battle confirmed that we are not double counting (we do not need to average). Need to ask Clear same questions to close out issue.
